[package]
name = "eekgit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.19.0"
clap = { version = "4.4.6", features = ["derive"] }
flate2 = "1.0.28"
sha1 = "0.10.6"
hex = "0.4.3"
